FROM python:3.11-buster

ENV PYTHONUNBUFFERD=1

WORKDIR /src

RUN pip install poetry

COPY pyproject.toml* poetry.lock* ./

# デプロイに必要
COPY api api
COPY entrypoint.sh ./

# portryでライブラリをインストール(pyproject.tomlがすでにある場合）
RUN poetry config virtualenvs.in-project true
RUN if [ -f pyproject.toml ]; then poetry install --no-root; fi

# DB migrationを実行し、uvicormサーバーを立ち上げる
ENTRYPOINT ["bash", "entrypoint.sh"]